#!/bin/bash
# Copyright 2013 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# vim:set ai sts=4 ts=4 sw=4 expandtab filetype=sh:

LOGFILE="${HOME}/external-browser.log"
RESULTS="${HOME}/external-browser.get"

echo "[$$] started: $( date ), cmdline: $@"    >>${LOGFILE}
wget --tries=3 --append-output=${LOGFILE} --output-document=${RESULTS} --no-verbose "$@"
echo "[$$] complete: $( date )"                >>${LOGFILE}

exit 0
